"""
Auto-generated model registry from Cherry Studio.
Source: https://github.com/CherryHQ/cherry-studio
Generated: 2026-06-02T10:45:33.247693+00:00

DO NOT EDIT MANUALLY - This file is auto-generated by GitHub Actions.
"""

# Static model lists for each provider
# Used when API key is not available for fetching models

PROVIDER_MODELS: dict[str, list[str]] = {
    "ph8": [
        "deepseek-v3-241226",
        "deepseek-r1-250120"
    ],
    "aihubmix": [
        "gpt-5",
        "gpt-5-mini",
        "gpt-5-nano",
        "gpt-5-chat-latest",
        "o3",
        "o4-mini",
        "gpt-4.1",
        "gpt-4o",
        "gpt-image-1",
        "gpt-image-2",
        "DeepSeek-V3",
        "DeepSeek-R1",
        "claude-sonnet-4-20250514",
        "gemini-2.5-pro",
        "gemini-2.5-flash-nothink",
        "gemini-2.5-flash",
        "Qwen3-235B-A22B-Instruct-2507",
        "kimi-k2-0711-preview",
        "Llama-4-Scout-17B-16E-Instruct",
        "Llama-4-Maverick-17B-128E-Instruct-FP8"
    ],
    "burncloud": [
        "claude-opus-4-5-20251101",
        "claude-sonnet-4-5-20250929",
        "claude-haiku-4-5-20251001",
        "gpt-5",
        "gpt-5.1",
        "gemini-2.5-flash",
        "gemini-2.5-flash-image",
        "gemini-2.5-pro",
        "gemini-3-pro-preview",
        "deepseek-reasoner",
        "deepseek-chat"
    ],
    "silicon": [
        "deepseek-ai/DeepSeek-V3.2",
        "Qwen/Qwen3-8B",
        "BAAI/bge-m3"
    ],
    "ppio": [
        "deepseek/deepseek-v3.2",
        "minimax/minimax-m2",
        "qwen/qwen3-235b-a22b-instruct-2507",
        "qwen/qwen3-vl-235b-a22b-instruct",
        "qwen/qwen3-embedding-8b",
        "qwen/qwen3-reranker-8b"
    ],
    "openai": [
        "gpt-5.4",
        "gpt-5.4-pro",
        "gpt-5.2",
        "gpt-5.2-pro",
        "gpt-5.1",
        "gpt-5",
        "gpt-5-pro",
        "gpt-5-chat",
        "gpt-image-1"
    ],
    "gemini": [
        "gemini-2.5-flash",
        "gemini-2.5-pro",
        "gemini-2.5-flash-image-preview",
        "gemini-3-pro-image-preview",
        "gemini-3-pro-preview",
        "gemini-3.1-pro-preview"
    ],
    "anthropic": [
        "claude-opus-4-7",
        "claude-opus-4-6",
        "claude-sonnet-4-6",
        "claude-sonnet-4-5",
        "claude-haiku-4-5",
        "claude-opus-4-5"
    ],
    "deepseek": [
        "deepseek-v4-flash",
        "deepseek-v4-pro"
    ],
    "together": [
        "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo",
        "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo",
        "google/gemma-2-27b-it",
        "google/gemma-2-9b-it"
    ],
    "ocoolai": [
        "deepseek-chat",
        "deepseek-reasoner",
        "deepseek-ai/DeepSeek-R1",
        "HiSpeed/DeepSeek-R1",
        "ocoolAI/DeepSeek-R1",
        "Azure/DeepSeek-R1",
        "gpt-4o",
        "gpt-4o-all",
        "gpt-4o-mini",
        "gpt-4",
        "o1-preview",
        "o1-mini",
        "claude-3-5-sonnet-20240620",
        "claude-3-5-haiku-20241022",
        "gemini-pro",
        "gemini-1.5-pro",
        "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo",
        "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo",
        "meta-llama/Llama-3.2-3B-Vision-Instruct-Turbo",
        "google/gemma-2-27b-it",
        "google/gemma-2-9b-it",
        "Doubao-embedding",
        "text-embedding-3-large",
        "text-embedding-3-small",
        "text-embedding-v2"
    ],
    "github": [
        "gpt-4o"
    ],
    "copilot": [
        "gpt-5-mini"
    ],
    "yi": [
        "yi-lightning",
        "yi-vision-v2"
    ],
    "zhipu": [
        "glm-5",
        "glm-4.7",
        "glm-4.5-flash",
        "glm-4.6",
        "glm-4.6v",
        "glm-4.6v-flash",
        "glm-4.6v-flashx",
        "glm-4.7",
        "glm-4.5",
        "glm-4.5-air",
        "glm-4.5-airx",
        "glm-4.5v",
        "embedding-3",
        "cogView-4-250304"
    ],
    "moonshot": [
        "moonshot-v1-auto"
    ],
    "baichuan": [
        "Baichuan4",
        "Baichuan3-Turbo",
        "Baichuan3-Turbo-128k",
        "Baichuan4-Turbo",
        "Baichuan4-Air",
        "Baichuan-M2",
        "Baichuan-M2-Plus",
        "Baichuan-M3",
        "Baichuan-M3-Plus"
    ],
    "modelscope": [
        "Qwen/Qwen2.5-72B-Instruct",
        "Qwen/Qwen2.5-VL-72B-Instruct",
        "Qwen/Qwen2.5-Coder-32B-Instruct",
        "deepseek-ai/DeepSeek-R1",
        "deepseek-ai/DeepSeek-V3"
    ],
    "dashscope": [
        "qwen3.5-plus",
        "qwen3.5-flash",
        "qwen3-max",
        "kimi-k2.5",
        "glm-5",
        "MiniMax/MiniMax-M2.5",
        "deepseek-v3.2"
    ],
    "stepfun": [
        "step-1-8k",
        "step-1-flash"
    ],
    "doubao": [
        "doubao-seed-1-8-251228",
        "doubao-1-5-vision-pro-32k-250115",
        "doubao-1-5-pro-32k-250115",
        "doubao-1-5-pro-32k-character-250228",
        "doubao-1-5-pro-256k-250115",
        "deepseek-r1-250120",
        "deepseek-r1-distill-qwen-32b-250120",
        "deepseek-r1-distill-qwen-7b-250120",
        "deepseek-v3-250324",
        "doubao-pro-32k-241215",
        "doubao-pro-32k-functioncall-241028",
        "doubao-pro-32k-character-241215",
        "doubao-pro-256k-241115",
        "doubao-lite-4k-character-240828",
        "doubao-lite-32k-240828",
        "doubao-lite-32k-character-241015",
        "doubao-lite-128k-240828",
        "doubao-1-5-lite-32k-250115",
        "doubao-embedding-large-text-240915",
        "doubao-embedding-text-240715",
        "doubao-embedding-vision-241215",
        "doubao-vision-lite-32k-241015",
        "doubao-seed-2-0-pro-260215",
        "doubao-seed-2-0-lite-260215",
        "doubao-seed-2-0-code-preview-260215",
        "doubao-seed-2-0-mini-260215"
    ],
    "minimax": [
        "MiniMax-M2.7",
        "MiniMax-M2.7-highspeed",
        "MiniMax-M2.5",
        "MiniMax-M2.5-highspeed",
        "MiniMax-M2.5-lightning",
        "MiniMax-M2.1",
        "MiniMax-M2.1-lightning",
        "MiniMax-M2",
        "M2-her"
    ],
    "hyperbolic": [
        "Qwen/Qwen2-VL-72B-Instruct",
        "Qwen/Qwen2-VL-7B-Instruct",
        "mistralai/Pixtral-12B-2409",
        "meta-llama/Meta-Llama-3.1-405B"
    ],
    "grok": [
        "grok-4.3",
        "grok-4",
        "grok-3",
        "grok-3-fast",
        "grok-3-mini",
        "grok-3-mini-fast"
    ],
    "mistral": [
        "pixtral-12b-2409"
    ],
    "jina": [
        "jina-clip-v1",
        "jina-clip-v2",
        "jina-embeddings-v2-base-en",
        "jina-embeddings-v2-base-es",
        "jina-embeddings-v2-base-de",
        "jina-embeddings-v2-base-zh",
        "jina-embeddings-v2-base-code",
        "jina-embeddings-v3"
    ],
    "fireworks": [
        "accounts/fireworks/models/mythomax-l2-13b",
        "accounts/fireworks/models/llama-v3-70b-instruct"
    ],
    "hunyuan": [
        "hunyuan-pro",
        "hunyuan-standard",
        "hunyuan-lite",
        "hunyuan-standard-256k",
        "hunyuan-vision",
        "hunyuan-code",
        "hunyuan-role",
        "hunyuan-turbo",
        "hunyuan-turbos-latest",
        "hunyuan-embedding"
    ],
    "nvidia": [
        "01-ai/yi-large",
        "meta/llama-3.1-405b-instruct"
    ],
    "openrouter": [
        "google/gemini-2.5-flash-image-preview",
        "google/gemini-2.5-flash-preview",
        "qwen/qwen-2.5-7b-instruct:free",
        "deepseek/deepseek-chat",
        "mistralai/mistral-7b-instruct:free"
    ],
    "groq": [
        "llama3-8b-8192",
        "llama3-70b-8192",
        "mistral-saba-24b",
        "gemma-9b-it"
    ],
    "dmxapi": [
        "Qwen/Qwen2.5-7B-Instruct",
        "ERNIE-Speed-128K",
        "gpt-4o",
        "gpt-4o-mini",
        "DMXAPI-DeepSeek-R1",
        "DMXAPI-DeepSeek-V3",
        "claude-3-5-sonnet-20241022",
        "gemini-2.0-flash"
    ],
    "perplexity": [
        "sonar-reasoning-pro",
        "sonar-reasoning",
        "sonar-pro",
        "sonar",
        "sonar-deep-research"
    ],
    "infini": [
        "deepseek-r1",
        "deepseek-r1-distill-qwen-32b",
        "deepseek-v3",
        "qwen2.5-72b-instruct",
        "qwen2.5-32b-instruct",
        "qwen2.5-14b-instruct",
        "qwen2.5-7b-instruct",
        "qwen2-72b-instruct",
        "qwq-32b-preview",
        "qwen2.5-coder-32b-instruct",
        "llama-3.3-70b-instruct",
        "bge-m3",
        "gemma-2-27b-it",
        "jina-embeddings-v2-base-zh",
        "jina-embeddings-v2-base-code"
    ],
    "voyageai": [
        "voyage-3-large",
        "voyage-3",
        "voyage-3-lite",
        "voyage-code-3",
        "voyage-finance-3",
        "voyage-law-2",
        "voyage-code-2",
        "rerank-2",
        "rerank-2-lite"
    ],
    "qiniu": [
        "deepseek-r1",
        "deepseek-r1-search",
        "deepseek-r1-32b",
        "deepseek-v3",
        "deepseek-v3-search",
        "deepseek-v3-tool",
        "qwq-32b",
        "qwen2.5-72b-instruct"
    ],
    "tokenflux": [
        "gpt-4.1",
        "gpt-4.1-mini",
        "claude-sonnet-4",
        "claude-3-7-sonnet",
        "gemini-2.5-pro",
        "gemini-2.5-flash",
        "deepseek-r1",
        "deepseek-v3",
        "qwen-max",
        "qwen-plus"
    ],
    "cephalon": [
        "DeepSeek-R1"
    ],
    "lanyun": [
        "/maas/deepseek-ai/DeepSeek-R1-0528",
        "/maas/deepseek-ai/DeepSeek-V3-0324",
        "/maas/qwen/Qwen2.5-72B-Instruct",
        "/maas/qwen/Qwen3-235B-A22B",
        "/maas/minimax/MiniMax-M1-80k",
        "/maas/google/Gemma3-27B"
    ],
    "poe": [
        "Claude-Opus-4.6",
        "Claude-Sonnet-4.6",
        "Claude-Haiku-4.5",
        "GPT-5.4",
        "GPT-5.3-Codex",
        "GPT-5.2",
        "GPT-5.2-Codex",
        "GPT-5.1",
        "Gemini-3.1-Pro",
        "Grok-4",
        "DeepSeek-R1",
        "Kimi-K2.5",
        "Kimi-K2-Thinking"
    ],
    "aionly": [
        "claude-opus-4-6",
        "claude-haiku-4-5-20251001",
        "claude-sonnet-4-6",
        "gpt-5.4",
        "gpt-5.4-mini",
        "gpt-5.4-nano",
        "gemini-3.1-flash-lite-preview",
        "gemini-3.1-pro-preview",
        "gemini-2.5-pro",
        "gemini-2.5-flash"
    ],
    "longcat": [
        "LongCat-Flash-Chat",
        "LongCat-Flash-Thinking"
    ],
    "cerebras": [
        "gpt-oss-120b",
        "zai-glm-4.6",
        "qwen-3-235b-a22b-instruct-2507"
    ],
    "mimo": [
        "mimo-v2.5",
        "mimo-v2.5-pro",
        "mimo-v2-flash",
        "mimo-v2-omni"
    ],
    "zai": [
        "glm-5",
        "glm-4.7",
        "glm-4.5-flash",
        "glm-4.6",
        "glm-4.6v",
        "glm-4.6v-flash",
        "glm-4.5",
        "glm-4.5-air",
        "glm-4.5v"
    ]
}


def get_static_models(provider: str) -> list[str]:
    """
    Get static model list for a provider.
    
    Args:
        provider: Provider name (e.g., 'openai', 'anthropic')
        
    Returns:
        List of model IDs, empty list if provider not found
    """
    return PROVIDER_MODELS.get(provider.lower(), [])


def get_all_providers() -> list[str]:
    """Get list of all providers with static models"""
    return list(PROVIDER_MODELS.keys())


def search_models(query: str) -> list[dict[str, str]]:
    """
    Search models across all providers.
    
    Args:
        query: Search query (matched against model ID)
        
    Returns:
        List of dicts with 'provider' and 'model_id' keys
    """
    results = []
    query_lower = query.lower()
    
    for provider, models in PROVIDER_MODELS.items():
        for model_id in models:
            if query_lower in model_id.lower():
                results.append({"provider": provider, "model_id": model_id})
    
    return results
