"""
从 Cherry Studio 提取模型列表，生成 Python 硬编码文件。

Cherry Studio 的模型定义在:
src/renderer/src/config/models/default.ts

格式:
export const SYSTEM_MODELS: Record<string, Model[]> = {
  openai: [
    { id: 'gpt-4o', name: 'GPT-4o', provider: 'openai', group: 'GPT 4o' },
    ...
  ],
  ...
}
"""

import json
import re
from pathlib import Path
from datetime import datetime, timezone

import os

CHERRY_MODELS_FILE = Path(os.environ.get("CHERRY_MODELS_DIR", "cherry-studio/src/renderer/src/config/models")) / "default.ts"
OUTPUT_FILE = Path("src/providers/models_registry.py")


def extract_models_from_ts(file_path: Path) -> dict[str, list[str]]:
    """从 TypeScript 文件提取模型列表"""
    if not file_path.exists():
        print(f"Error: {file_path} not found")
        return {}
    
    content = file_path.read_text(encoding='utf-8')
    models_map = {}
    
    # 匹配 provider 数组块
    # 格式: providerName: [
    #   { id: 'model-id', name: '...', ... },
    #   ...
    # ]
    provider_pattern = r"(\w+(?:-\w+)*)\s*:\s*\[(.*?)\]"
    
    for match in re.finditer(provider_pattern, content, re.DOTALL):
        provider_name = match.group(1)
        provider_block = match.group(2)
        
        # 跳过非 provider 的字段
        if provider_name in ('defaultModel', 'SYSTEM_MODELS'):
            continue
        
        # 提取模型 ID
        # 格式: { id: 'model-id', ... }
        id_pattern = r"id:\s*['\"]([^'\"]+)['\"]"
        model_ids = []
        
        for id_match in re.finditer(id_pattern, provider_block):
            model_id = id_match.group(1)
            model_ids.append(model_id)
        
        if model_ids:
            models_map[provider_name] = model_ids
    
    return models_map


def main():
    print("Extracting models from Cherry Studio...")
    print(f"Source: {CHERRY_MODELS_FILE}")
    
    if not CHERRY_MODELS_FILE.exists():
        print(f"Error: {CHERRY_MODELS_FILE} not found!")
        print("Please run the cherry-studio checkout first.")
        return 1
    
    models_map = extract_models_from_ts(CHERRY_MODELS_FILE)
    
    if not models_map:
        print("Error: No models extracted!")
        return 1
    
    # 统计
    total_models = sum(len(v) for v in models_map.values())
    print(f"Extracted {total_models} models from {len(models_map)} providers")
    
    # 生成 Python 文件
    timestamp = datetime.now(timezone.utc).isoformat()
    models_json = json.dumps(models_map, indent=4, ensure_ascii=False)
    
    output = f'''"""
Auto-generated model registry from Cherry Studio.
Source: https://github.com/CherryHQ/cherry-studio
Generated: {timestamp}

DO NOT EDIT MANUALLY - This file is auto-generated by GitHub Actions.
"""

# Static model lists for each provider
# Used when API key is not available for fetching models

PROVIDER_MODELS: dict[str, list[str]] = {models_json}


def get_static_models(provider: str) -> list[str]:
    """
    Get static model list for a provider.
    
    Args:
        provider: Provider name (e.g., 'openai', 'anthropic')
        
    Returns:
        List of model IDs, empty list if provider not found
    """
    return PROVIDER_MODELS.get(provider.lower(), [])


def get_all_providers() -> list[str]:
    """Get list of all providers with static models"""
    return list(PROVIDER_MODELS.keys())


def search_models(query: str) -> list[dict[str, str]]:
    """
    Search models across all providers.
    
    Args:
        query: Search query (matched against model ID)
        
    Returns:
        List of dicts with 'provider' and 'model_id' keys
    """
    results = []
    query_lower = query.lower()
    
    for provider, models in PROVIDER_MODELS.items():
        for model_id in models:
            if query_lower in model_id.lower():
                results.append({{"provider": provider, "model_id": model_id}})
    
    return results
'''
    
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output, encoding='utf-8')
    
    print(f"\nOutput: {OUTPUT_FILE}")
    print(f"Providers: {', '.join(sorted(models_map.keys()))}")
    
    return 0


if __name__ == "__main__":
    exit(main())
