"""
从 Cherry Studio 的 JSON 数据提取模型列表，生成 Python 硬编码文件。

Cherry Studio 新路径:
packages/provider-registry/data/models.json

用法: python scripts/extract_models.py
"""

import json
import os
from pathlib import Path
from datetime import datetime, timezone

# 新路径：JSON 数据文件
CHERRY_DATA_DIR = Path(os.environ.get("CHERRY_DATA_DIR", "cherry-studio/packages/provider-registry/data"))
MODELS_FILE = CHERRY_DATA_DIR / "models.json"
OUTPUT_FILE = Path("src/providers/models_registry.py")


def extract_models_from_json(file_path: Path) -> dict[str, list[str]]:
    """从 JSON 文件提取模型列表，按 ownedBy 分组"""
    if not file_path.exists():
        print(f"Error: {file_path} not found")
        return {}

    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    models = data.get("models", [])

    # 按 ownedBy 分组
    provider_models = {}
    for model in models:
        model_id = model.get("id", "")
        owned_by = model.get("ownedBy", "unknown")

        if not model_id:
            continue

        if owned_by not in provider_models:
            provider_models[owned_by] = []

        provider_models[owned_by].append(model_id)

    return provider_models


def main():
    print("Extracting models from Cherry Studio JSON...")
    print(f"Source: {MODELS_FILE}")

    if not MODELS_FILE.exists():
        print(f"Error: {MODELS_FILE} not found!")
        print("Please run the cherry-studio checkout first.")
        return 1

    provider_models = extract_models_from_json(MODELS_FILE)

    if not provider_models:
        print("Error: No models extracted!")
        return 1

    # 统计
    total_models = sum(len(v) for v in provider_models.values())
    print(f"Extracted {total_models} models from {len(provider_models)} providers")

    # 生成 Python 文件
    timestamp = datetime.now(timezone.utc).isoformat()
    models_json = json.dumps(provider_models, indent=4, ensure_ascii=False)

    output = f'''"""
Auto-generated model registry from Cherry Studio.
Source: https://github.com/CherryHQ/cherry-studio
Generated: {timestamp}

DO NOT EDIT MANUALLY - This file is auto-generated by GitHub Actions.
"""

# Static model lists for each provider
# Used when API key is not available for fetching models

PROVIDER_MODELS: dict[str, list[str]] = {models_json}


def get_static_models(provider: str) -> list[str]:
    """
    Get static model list for a provider.

    Args:
        provider: Provider name (e.g., 'openai', 'anthropic')

    Returns:
        List of model IDs, empty list if provider not found
    """
    return PROVIDER_MODELS.get(provider.lower(), [])


def get_all_providers() -> list[str]:
    """Get list of all providers with static models"""
    return list(PROVIDER_MODELS.keys())


def search_models(query: str) -> list[dict[str, str]]:
    """
    Search models across all providers.

    Args:
        query: Search query (matched against model ID)

    Returns:
        List of dicts with 'provider' and 'model_id' keys
    """
    results = []
    query_lower = query.lower()

    for provider, models in PROVIDER_MODELS.items():
        for model_id in models:
            if query_lower in model_id.lower():
                results.append({{"provider": provider, "model_id": model_id}})

    return results
'''

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"\nOutput: {OUTPUT_FILE}")
    print(f"Providers: {', '.join(sorted(provider_models.keys()))}")

    return 0


if __name__ == "__main__":
    exit(main())
